### PR TITLE
fix: relative locktime bug

### LINKED ISSUE #255: [bug] Client fails on block 757753: Relative block-based lock time is not respected
### Description
In `packages/client` command:
```
scarb test --forceall tests/data/full_757752.json
```
fails with:
```
Panicked with 'Relative block-based lock time is not respected: current height 757753, outpoint height 757752, lock time 1 blocks'
```

### PR DESCRIPTION
**Pull request by bloomingpeach**
- [ ] resolves #255 
- [x] follows contribution [guide](https://github.com/keep-starknet-strange/raito/blob/main/CONTRIBUTING.md)
- [ ] code change includes tests

Add support for running the integration scripts on MacOS.
Fixes #255 

```
(.venv) client % scarb test --forceall tests/data/full_757752.json

     Running test client (scarb build && ../../scripts/data/integration_tests.sh)
    Finished `dev` profile target(s) in 9 seconds
running integration tests ...
test tests/data/full_757752.json ... ok (gas usage est.: 13975561509)
```

### CODE REVIEW

**Review by m-kus — APPROVED** [review]

**Comment by m-kus** [comment]
@bloomingpeach can you please add the full_757752 test file from https://github.com/keep-starknet-strange/raito/pull/195/files ?

**Comment by bloomingpeach** [comment]
Hi @m-kus the `full_757752` is already available on the `mk/script` branch

**Comment by m-kus** [comment]
> Hi @m-kus the `full_757752` test is already available on the `mk/script` branch

I know, but we need it to test the fix in the CI pipeline

**Comment by bloomingpeach** [comment]
Sorry I don't quite get that @m-kus, what should I do. btw this PR I am merging to `mk/script, not `main` branch. Please let me know should I change the base branch to `main`

**Comment by m-kus** [comment]
Ah ok, I didn't notice, sorry
All good then, @maciejka pls take a look

**Comment by maciejka** [comment]
@bloomingpeach this pr has been closed by mistake. You changes were merged in: #262.

**Pull request closed without merging**
