### PR TITLE
Fix Typos

### PR DESCRIPTION
**Pull request by VolodymyrBg**
- [x] Fixed errors ( typos, grammatical mistakes )
- [x] follows contribution [guide](https://github.com/keep-starknet-strange/raito/blob/main/CONTRIBUTING.md)

Fixed errors and inaccuracies in the project's textual materials.
Improved readability of texts and documentation.

### CODE REVIEW

**Review by maciejka — APPROVED** [review]

**Comment by VolodymyrBg** [comment]
@maciejka I'm glad that I was useful. Could you please merge it?

**Comment by maciejka** [comment]
> @maciejka I'm glad that I was useful. Could you please merge it?

Please fix formating issue.

**Comment by VolodymyrBg** [comment]
@maciejka 

> > @maciejka I'm glad that I was useful. Could you please merge it?
> 
> Please fix formating issue.

how to do that?

**Comment by VolodymyrBg** [comment]
> > @maciejka I'm glad that I was useful. Could you please merge it?
> 
> Please fix formating issue.

Done. As it seems to me

**Comment by maciejka** [comment]
> > > @maciejka I'm glad that I was useful. Could you please merge it?
> > 
> > 
> > Please fix formating issue.
> 
> Done. As it seems to me

Please do `scarb fmt`

**Comment by VolodymyrBg** [comment]
> > > > @maciejka I'm glad that I was useful. Could you please merge it?
> > > 
> > > 
> > > Please fix formating issue.
> > 
> > 
> > Done. As it seems to me
> 
> Please do `scarb fmt`
Done

**Comment by maciejka** [comment]
@VolodymyrBg Thanks!

**Pull request merged**
