### PR TITLE
test cases for invalid input sequence (relative locktime)

### LINKED ISSUE #178: [dev] Add tests for invalid input sequence (relative locktime)
Currently there are unit tests that cover happy path when relative locktime regulated by input sequence is respected.  
We need to also include tests for unhappy paths.

Extend `locktime.cairo` with several tests that cover scenarios both for time & height based locktimes.

Reading: https://learnmeabitcoin.com/technical/transaction/input/sequence/ (see Relative Locktime section)

### PR DESCRIPTION
**Pull request by mubarak23**
- [x] resolves #178 
- [x] follows contribution [guide](https://github.com/keep-starknet-strange/raito/blob/main/CONTRIBUTING.md)
- [x] code change includes tests

### CODE REVIEW

**Review by maciejka — CHANGES_REQUESTED** [review]
Add more meaningful test names and use:
```
 #[should_panic(expected: ("...",))]
```
To specify expected errors.

**Comment by mubarak23** [comment]
> should_panic

we can't use `should_panic`

we are returning a ByteArray containing the error message  not panic

**Comment by maciejka** [comment]
> > should_panic
> 
> we can't use `should_panic`
> 
> we are returning a ByteArray containing the error message not panic

Use unwrap(), on the result it will panic. Or you can destruct the error to get the error message.

**Review by maciejka — CHANGES_REQUESTED** [review]
Please add expected errors with: `#[should_panic(expected: ("...",))]`.
Make test names more meaningful, for example:
`test_fail_relative_locktime_enabled_block_height` -> `test_relative_locktime_block_height_lt_relative_locktime`

**Comment by mubarak23** [comment]
> (expected: ("...",))

am getting the following error 

`
Result::unwrap failed.`

am setting this 

` #[should_panic(expected: ("Relative block-based lock time is not respected: current height 603019, outpoint height 603018, lock time 144 blocks",))]`

**Review by maciejka — APPROVED** [review]

**Pull request merged**
